version: "3.8"

services:
  app:
    build: .
#    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    links:
      - mysql

  mysql:
    image: mysql
#    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bcpedia

