spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bcpedia
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    general-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
