@startuml usecase4
mainframe uc resign

:validatorA: as va <<EOA>>

package BCPediaPeriphery as pp <<SC>> {
    usecase resign as rs
    usecase review as rv
}

package BCPediaTokens <<ERC1155>> {
    usecase balanceOf as bo
    usecase burn as bu
    usecase setApprovalForAll as sa
    usecase transferFrom as tf
}

usecase punishEvent as pe

note "Simplified procedures" as n1

va --> rs
va --> sa
pe --> rv
rv --> bo
bo ..> va
rv --> rs : if less than threshold

rs --> bu : burn certificate
rs --> tf

tf ..> va : return remaining stake

@enduml